#
# Copyright (c) 2026 Taalam Innovations KE. All rights reserved.
# Confidential and proprietary.
#

taalam.tenant.runtime.enabled=${TAALAM_TENANT_RUNTIME_ENABLED:false}
taalam.tenant.runtime.oauth2.issuer-uri=${TAALAM_TENANT_RUNTIME_OAUTH2_ISSUER_URI:}
taalam.tenant.runtime.oauth2.jwk-set-uri=${TAALAM_TENANT_RUNTIME_OAUTH2_JWK_SET_URI:}
taalam.tenant.runtime.oauth2.audience=${TAALAM_TENANT_RUNTIME_OAUTH2_AUDIENCE:fineract}
taalam.tenant.runtime.oauth2.required-authority=${TAALAM_TENANT_RUNTIME_OAUTH2_REQUIRED_AUTHORITY:TENANT_RUNTIME_REGISTER}
taalam.tenant.runtime.authentication-verification-enabled=${TAALAM_TENANT_RUNTIME_AUTHENTICATION_VERIFICATION_ENABLED:false}
taalam.tenant.runtime.authentication-verification-username=${TAALAM_TENANT_RUNTIME_AUTHENTICATION_VERIFICATION_USERNAME:mifos}
taalam.tenant.runtime.authentication-verification-password=${TAALAM_TENANT_RUNTIME_AUTHENTICATION_VERIFICATION_PASSWORD:password}
