/*
 * Copyright (c) 2026 Taalam Innovations KE. All rights reserved.
 * Confidential and proprietary.
 */

dependencies {
    implementation(project(':fineract-core'))
    implementation(project(':fineract-provider'))
    implementation(project(':fineract-security'))
    implementation('com.fasterxml.jackson.core:jackson-databind')
    implementation('com.google.code.gson:gson')
    implementation('com.zaxxer:HikariCP')
    implementation('jakarta.ws.rs:jakarta.ws.rs-api')
    implementation('org.liquibase:liquibase-core')
    implementation('org.springframework.boot:spring-boot-starter-security')
    implementation('org.springframework.boot:spring-boot-starter-oauth2-resource-server')
    implementation('org.springframework.boot:spring-boot-starter-data-jpa') {
        exclude group: 'org.hibernate'
    }
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.eclipse.persistence:org.eclipse.persistence.jpa') {
        exclude group: 'org.eclipse.persistence', module: 'jakarta.persistence'
    }
    implementation('org.springframework:spring-jdbc')
    compileOnly('org.springframework.boot:spring-boot-autoconfigure')
}
