/*
 * Copyright (c) 2026 Taalam Innovations KE. All rights reserved.
 * Confidential and proprietary.
 */
description = 'Taalam Fineract Keycloak Resource Server'

group = 'ke.co.taalaminnovations.fineract'

base {
    archivesName = 'taalam-fineract-keycloak-resource-server'
}

apply from: 'dependencies.gradle'
