/*
 * Copyright (c) 2026 Taalam Innovations KE. All rights reserved.
 * Confidential and proprietary.
 */

dependencies {
    implementation(project(':fineract-core'))
    implementation(project(':fineract-provider'))
    implementation(project(':fineract-security'))
    implementation(project(':custom:taalam:tenant:runtime'))
    implementation('org.keycloak:keycloak-admin-client:26.0.9')
    implementation('org.springframework.boot:spring-boot-starter-oauth2-resource-server')
    implementation('org.springframework.boot:spring-boot-starter-security')
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.springframework:spring-tx')
    compileOnly('org.springframework.boot:spring-boot-autoconfigure')
    testImplementation('com.google.code.gson:gson')
}
